name: location_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # flutter_sdk:
  #   path: path/to/flutter/packages/flutter_sdk

  firebase_core: ^2.30.1

  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  user_repository: 
    path: packages/user_repository

  cupertino_icons: ^1.0.8
  geolocator: ^11.0.0
  google_maps_flutter: ^2.6.1
  firebase_auth: ^4.19.4
  cloud_firestore: ^4.17.2
  firebase_database: ^10.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
