// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq9CRHHbDUVDXS_CalPFCIFKj_qJL7EyM',
    appId: '1:472617774709:web:06f132ec58314ac408d23c',
    messagingSenderId: '472617774709',
    projectId: 'locate-me-e96ee',
    authDomain: 'locate-me-e96ee.firebaseapp.com',
    storageBucket: 'locate-me-e96ee.appspot.com',
    measurementId: 'G-QMBF37CWXS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6SJTeZ0q-L_3-P5EUwBc_atD4bjPqOTI',
    appId: '1:472617774709:android:c607859c80f4eeb008d23c',
    messagingSenderId: '472617774709',
    projectId: 'locate-me-e96ee',
    storageBucket: 'locate-me-e96ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWXcwx6wZN3Lq97dwCwqOOgnuKoLHP1dQ',
    appId: '1:472617774709:ios:67dd6acb0c393efe08d23c',
    messagingSenderId: '472617774709',
    projectId: 'locate-me-e96ee',
    storageBucket: 'locate-me-e96ee.appspot.com',
    iosBundleId: 'com.example.locationApp',
  );
}
