// import 'dart:io';
// import 'package:firebase_core/firebase_core.dart';

// void main() async {
//   // Initialize Firebase app
//   await Firebase.initializeApp();

//   // Retrieve Firebase options
//   final FirebaseOptions options = Firebase.app().options;

//   // Generate Dart code for firebase_options.dart
//   final dartCode = '''
//   // This file is automatically generated. Do not modify.
  
//   import 'package:firebase_core/firebase_core.dart';

//   // Firebase options
//   FirebaseOptions firebaseOptions = FirebaseOptions(
//     apiKey: '${options.apiKey}',
//     appId: '${options.appId}',
//     messagingSenderId: '${options.messagingSenderId}',
//     projectId: '${options.projectId}',
//     authDomain: '${options.authDomain}',
//     databaseURL: '${options.databaseURL}',
//     storageBucket: '${options.storageBucket}',
//   );
//   ''';

//   // Write the Dart code to firebase_options.dart
//   final file = File('firebase_options.dart');
//   await file.writeAsString(dartCode);

//   print('firebase_options.dart generated successfully.');
// }
